{ ... }:

{
  programs.vscode.extensions = with pkgs.vscode-extensions;
    [
        4ops.packer
        4ops.terraform
        aaron-bond.better-comments
        adpyke.codesnap
        alexcvzz.-sqlite
        alexisvt.flutter-snippets
        amazonwebservices.aws-toolkit-
        Angular.ng-template
        bbenoist.Nix
        bbenoist.vagrant
        be5invis.-icontheme-nomo-dark
        bradlc.-tailwindcss
        christian-kohler.npm-intellisense
        ClemensPeters.format-json
        Dart-Code.dart-code
        Dart-Code.flutter
        dunstontc.-docker-syntax
        eamodio.gitlens
        emmanuelbeziat.-great-icons
        erd0s.terraform-autocomplete
        file-icons.file-icons
        formulahendry.auto-rename-tag
        foxundermoon.shell-format
        GitHub.remotehub
        github.-github-actions
        golang.go
        hashicorp.hcl
        hashicorp.terraform
        humao.rest-client
        Infracost.infracost
        IronGeek.-env
        jeff-hykin.better-shellscript-syntax
        kreativ-software.csharpextensions
        monokai.theme-monokai-pro-
        ms-azuretools.azure-dev
        ms-azuretools.-azureappservice
        ms-azuretools.-azurecontainerapps
        ms-azuretools.-azurefunctions
        ms-azuretools.-azureresourcegroups
        ms-azuretools.-azurestaticwebapps
        ms-azuretools.-azurestorage
        ms-azuretools.-azureterraform
        ms-azuretools.-bicep
        ms-azuretools.-cosmosdb
        ms-azuretools.-docker
        ms-dotnettools.csharp
        ms-dotnettools.-dotnet-runtime
        ms-kubernetes-tools.kind-
        ms-kubernetes-tools.-kubernetes-tools
        ms-python.isort
        ms-python.python
        ms-python.-pylance
        ms-toolsai.jupyter-keymap
        ms-toolsai.jupyter-renderers
        ms--remote.remote-containers
        ms--remote.remote-ssh
        ms--remote.remote-ssh-edit
        ms-.azure-account
        ms-.azure-repos
        ms-.azurecli
        ms-.makefile-tools
        ms-.remote-explorer
        ms-.remote-repositories
        ms-.-node-azure-pack
        msjsdiag.-react-native
        owenfarrell.-vault
        patcx.-nuget-gallery
        pjmiravalle.terraform-advanced-syntax-highlighting
        PKief.material-icon-theme
        PKief.material-product-icons
        Postman.postman-for-
        Rajeshwaran.developer-theme-dark
        redhat.java
        redhat.-openshift-connector
        redhat.-redhat-account
        redhat.-yaml
        run-at-scale.terraform-doc-snippets
        ryanolsonx.zenburn
        shakram02.bash-beautify
        shd101wyy.markdown-preview-enhanced
        styra.-styra
        szTheory.-packer-powertools
        Tailscale.-tailscale
        tfsec.tfsec
        tsandall.opa
        VisualStudioExptTeam.intellicode-api-usage-examples
        VisualStudioExptTeam.intellicode
        -icons-team.-icons
        wholroyd.jinja
        yzhang.markdown-all-in-one
    ];
}

